# Generated by Django 4.2.11 on 2024-05-17 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('Menu_ID', models.AutoField(primary_key=True, serialize=False)),
                ('name_ch', models.CharField(help_text='鹹酥雞', max_length=20, verbose_name='商品名稱（中文）')),
                ('name_EN', models.CharField(help_text='Taiwanese fried chicken', max_length=50, verbose_name='商品名稱（英文）')),
                ('name_Indonesian', models.CharField(help_text='Ayam Renyah Asin', max_length=100, verbose_name='商品名稱（印尼文）')),
            ],
            options={
                'ordering': ['Menu_ID'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Order_ID', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(blank=True, help_text='件', max_length=10, verbose_name='單位名稱')),
                ('name_ch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menu')),
            ],
            options={
                'ordering': ['Order_ID'],
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('Factory_ID', models.AutoField(primary_key=True, serialize=False)),
                ('factory_name', models.CharField(max_length=10, verbose_name='廠商名稱')),
                ('name_ch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menu')),
            ],
            options={
                'ordering': ['Factory_ID'],
            },
        ),
    ]
