# Generated by Django 4.2.11 on 2024-05-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='訂購日期'),
        ),
    ]
