# Generated by Django 4.2.11 on 2024-05-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factory',
            name='name_ch',
        ),
        migrations.AddField(
            model_name='menu',
            name='Custom_unit',
            field=models.CharField(blank=True, help_text='份', max_length=10, verbose_name='販售單位'),
        ),
        migrations.AddField(
            model_name='menu',
            name='Factory_unit',
            field=models.CharField(blank=True, help_text='件', max_length=10, verbose_name='叫貨單位'),
        ),
        migrations.AddField(
            model_name='menu',
            name='factory_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.factory'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
