# Generated by Django 4.2.11 on 2024-05-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_factory_name_ch_menu_custom_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Custom_price',
            field=models.IntegerField(blank=True, help_text='50', null=True, verbose_name='販售價錢'),
        ),
        migrations.AddField(
            model_name='menu',
            name='Factory_price',
            field=models.IntegerField(blank=True, help_text='560', null=True, verbose_name='貨品價格'),
        ),
    ]
