# Generated by Django 4.2.11 on 2024-06-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_music_alter_menu_custom_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='store',
            fields=[
                ('Store_ID', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=10, verbose_name='分店名稱')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('phone', models.CharField(max_length=10, verbose_name='電話')),
            ],
            options={
                'ordering': ['Store_ID'],
            },
        ),
    ]
