# Generated by Django 4.2.11 on 2024-06-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_picture',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
