# Generated by Django 4.2.11 on 2024-06-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_menu_menu_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
