# Generated by Django 4.2.11 on 2024-07-04 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_menu_menu_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_types',
            fields=[
                ('Food_types_ID', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=10, verbose_name='食物類別')),
            ],
            options={
                'ordering': ['Food_types_ID'],
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='food_types',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.food_types'),
        ),
    ]
