# Generated by Django 4.2.11 on 2024-07-25 12:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_food_types_menu_food_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
